version: "3"

services:
  mysql:
    image: mysql:8.0.19
    ports: 
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - app
  
  rabbitmq:
    image: rabbitmq:3.8.2
    environment:
      # RABBITMQ_ERLANG_COOKIE: "aaaaaaaaaaaaa"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      RABBITMQ_DEFAULT_VHOST: "atfield"
    ports:
      - 127.0.0.1:15672:15672
      - 127.0.0.1:5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - app
      - worker

  redis:
    image: redis:5.0.7
    command: redis-server /etc/redis/redis.conf
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data
      - ./redis/redis.conf:/etc/redis/redis.conf
    networks:
      - app
      - worker

  elasticsearch:
    image: elasticsearch:6.8.6
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 127.0.0.1:9200:9200
    networks:
      - es

  kibana:
    image: kibana:6.8.6
    ports:
      - 127.0.0.1:5601:5601
    networks:
      - es

networks:
  app:
  worker:
  es:

volumes:
  mysql:
  redis:
  rabbitmq:
  elasticsearch:
